name: release

on: push

jobs:
  ubuntu-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      YML2_PATH: /home/runner/venv/bin
      PREFIX: /home/runner/install
    steps:
      - uses: actions/checkout@v4
      - name: Install ASN1C
        run: sudo apt install asn1c
      - name: Install yml2
        run: |
          python -m venv /home/runner/venv
          . /home/runner/venv/bin/activate
          pip install git+https://github.com/plancksecurity/foundation-yml2
      - name: Build
        run: |
          . /home/runner/venv/bin/activate
          make -j8
          make install
      - name: Compress
        run: |
          cd /home/runner/install
          tar cvj . > ../ubuntu-release.tar.bz2
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.head_ref || github.ref_name }}
          files: /home/runner/ubuntu-release.tar.bz2
          fail_on_unmatched_files: true

  windows-release:
    runs-on: windows-latest
    permissions:
      contents: write
    env:
      YML2PROC: 'C:\hostedtoolcache\windows\python\3.9.13\x64\Scripts\yml2proc.exe'
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.ALL_REPO_ACCESS_TOKEN }}
      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1.1
      - name: Install yml2
        run: |
          pip install git+https://github.com/plancksecurity/foundation-yml2
          pip list -v
          python -m site --user-base
          dir 'C:\hostedtoolcache\windows\python\3.9.13\x64\Scripts'
      - name: Build
        run: msbuild build-windows\libpEpTransport.vcxproj /p:Configuration=Release
      - name: Compress
        run: Compress-Archive -Path build-windows\Release\* -Destination windows-release.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.head_ref || github.ref_name }}
          files: windows-release.zip
          fail_on_unmatched_files: true

